#!/bin/sh
# counts instructions for a standard workload
set -e

OUTFILE="cachegrind.blutgang.`git describe --always --dirty`-`date +%s`"

rm -rf default.sled || true

CARGO_PROFILE_RELEASE_DEBUG=true \
cargo build \
  --bin=blutgang \
  --release   \
  --config example_config.toml

valgrind \
  --tool=cachegrind \
  --cachegrind-out-file=$OUTFILE \
  timeout 60s ./target/release/blutgang  --config example_config.toml 

LAST=`ls -t cachegrind.stress.* | sed -n 2p`


echo "Last cachegrind output: $LAST new file: $OUTFILE"

echo "--------------------------------------------"
echo "changes in instruction count"
cg_annotate --diff $LAST $OUTFILE | tail -1

